# arxivの学問領域の指定
subject: 'cat:astro-ph.*'

# 検索キーワード
keywords:
        Protoplanetary disks: 3
        Protoplanetary Disks: 3
        Protoplanetary Disk: 3
        protoplanetary disk: 3
        protoplanetary disks: 3
        Protoplanetary disc: 3
        Protoplanetary discs: 3
        Protoplanetary Disc: 3
        Protoplanetary Discs: 3
        protoplanetary disc: 3
        protoplanetary discs: 3
        Protostar: 3
        Protostars: 3
        protostar: 3
        protostars: 3
        Protostellar disk: 3
        Protostellar disks: 3
        Protostellar Disk: 3
        Protostellar Disks: 3
        protostellar disk: 3
        protostellar disks: 3
        Protostellar: 2
        protostellar: 2
        Debris disk: 1
        Debris disks: 1
        debris disk: 1
        debris disks: 1
        Debris disc: 1
        Debris discs: 1
        debris disc: 1
        debris discs: 1
        Star formation: 1
        star formation: 1
        Planet formation: 1
        planet formation: 1
        disk formation: 1
        circumstellar disk: 1
        circumstellar disks: 1
        circumbinary disk: 1
        circumbinary disks: 1
        protoplanet: 1
        exoplanet: 1
        Exoplanet: 1

# 通知の閾値
score_threshold: 0
